# -*- coding: utf-8 -*-
"""Code Clause Task -1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M08Q7DuAhNm45zv7kG0mPxwxZLSHeBQt

# Anurag Mishra
 **TASK 1**

 Stock Market Prediction
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data =pd.read_csv('/content/ADANIPORTS.csv')
data

data.isnull().sum()

data.dropna()

data.info()

new_data =data[['Open','High','Low','Close','Volume']]

"""# Feature Scaling



---
Preprcessing the Data
For performance improvement
"""

from sklearn.preprocessing  import StandardScaler
scalar=StandardScaler()
scale_feature=scalar.fit_transform(new_data)
scaled_data = pd.DataFrame(scale_feature,columns=new_data.columns)

"""# Splitting The Data Set"""

from sklearn.model_selection import train_test_split
X=scaled_data.drop('Close',axis=1)
Y=scaled_data['Close'] #Target Variable
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

print(X.shape)
print(Y.shape)

"""Training The Data"""

from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,Y_train)

from sklearn.metrics import mean_squared_error

Y_pred=model.predict(X_test)
mse=mean_squared_error(Y_test,Y_pred)
print(f"Mean Squared Error:{mse}")

"""# Data Visualization

Name of The Stocks
"""

name = data['Symbol'].unique()
print(name)

data['Date'] = pd.to_datetime(data['Date'])
for symbol in name :
  stock_data = data[data['Symbol'] == symbol]

# Plotting
  plt.figure(figsize=(12, 6))
  plt.plot(stock_data['Date'], stock_data['Close'], label='Closing Price', color='blue')
  plt.title(f'Stock {symbol} Closing Prices')
  plt.xlabel('Date')
  plt.ylabel('Price')
  plt.legend()
  plt.grid()
  plt.show()



